name: Build & Release PlantCareCalc+

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Вивести автора коміту
      run: |
        echo "Автор: ${{ github.actor }}"
        echo "Повідомлення коміту: ${{ github.event.head_commit.message }}"

    - name: Checkout репозиторію
      uses: actions/checkout@v4

    - name: Перейти в папку проєкту
      run: cd PlantCareCalcPlus

    - name: Встановити Qt6
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        cache: true

    - name: Встановити CMake
      uses: lukka/get-cmake@v3.28.3

    - name: Зібрати проєкт
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$ENV{QT_PATH}"
        cmake --build . --config Release

    - name: Створити реліз
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: PlantCareCalc+ v${{ github.run_number }}
        body: |
          Автоматичний реліз
          Автор: @${{ github.actor }}
          Коміт: ${{ github.event.head_commit.message }}
        files: PlantCareCalcPlus/build/Release/PlantCareCalcPlus.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
